import Head from 'next/head'
import Header from "@/components/header/Header";
import Main from "@/components/main/Main";
import Footer from "@/components/footer/Footer";

export default function Home() {
  return (
      <div>
        <Head>
          <title>internet-shop</title>
          <meta name="description" content="Generated by create next app"/>
          <meta name="viewport" content="width=device-width, initial-scale=1"/>
          <link rel="icon" href="/favicon.ico"/>
        </Head>
        <Header/>
        <Main/>
        <Footer/>
      </div>
  );
}
